### ISSUE TITLE
你好，反馈一个月份问题

### ISSUE THREAD

**Issue by easykline** [taynpg/csp#1]
![image](https://github.com/taynpg/csp/assets/132242696/a077ec08-3463-4990-a89b-40a19b5d4d69)

如图，在其他软件商月份都是显示己巳月，这个工具显示的是庚午月，这个月份好像是涉及到“交节”的时间，19940606 06:01分是芒种的交节时间，在这之前的应该还是算己巳月的，不是庚午月吧？

**Comment by taynpg** [comment]
感谢您的反馈，我查一下。

**Comment by taynpg** [comment]
初步查询是寿星天文日历的问题，如下所示，使用查表法日历是正确的，我反馈给sxtwl作者：

![image](https://github.com/taynpg/csp/assets/59216127/4e376097-0fa2-498f-b08b-18173f783e10)

**Comment by taynpg** [comment]
在`sxtwl`作者群中询问确认了，`sxtwl`月干支没有考虑节气时间，这个问题需要`csp`自己判断，后面我有空了改一下，目前`v1.3.1`版本的查表法日历不受影响，`csp`修正此问题之前可以使用`-c 0`指定查表日历使用。

**Comment by easykline** [comment]
点个赞，你这么好的项目不弄个群呀^^

**Comment by taynpg** [comment]
问题已解决，请参照`v1.3.2`版本，暂时还没有群，后面如果有需要再说吧。
